# config context path to "/" by setting an empty string
server:
  contextPath:

# JACKSON
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true

jwt:
  header: Authorization
  secret: 91ON2xG3vv4whmCja9ThDw9Pn2Xz8mmd1f7h95MEkaU=
  expiration: 3600
route:
  authentication:
      register: api/register
      login: api/login
  user:
      details: api/user/details